/* Generated by Yosys 0.47+121 (git sha1 98b4affc4, g++ 13.2.0-23ubuntu4 -fPIC -O3) */

module demux_case(o0, o1, o2, o3, o4, o5, o6, o7, sel, i);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  wire _42_;
  wire _43_;
  wire _44_;
  wire _45_;
  wire _46_;
  input i;
  wire i;
  output o0;
  wire o0;
  output o1;
  wire o1;
  output o2;
  wire o2;
  output o3;
  wire o3;
  output o4;
  wire o4;
  output o5;
  wire o5;
  output o6;
  wire o6;
  output o7;
  wire o7;
  input [2:0] sel;
  wire [2:0] sel;
  wire [7:0] y_int;
  sky130_fd_sc_hd__and4b_1 _47_ (
    .A_N(_44_),
    .B(_35_),
    .C(_46_),
    .D(_45_),
    .X(_42_)
  );
  sky130_fd_sc_hd__and4b_1 _48_ (
    .A_N(_45_),
    .B(_44_),
    .C(_35_),
    .D(_46_),
    .X(_41_)
  );
  sky130_fd_sc_hd__and4b_1 _49_ (
    .A_N(_46_),
    .B(_45_),
    .C(_44_),
    .D(_35_),
    .X(_39_)
  );
  sky130_fd_sc_hd__nor4bb_1 _50_ (
    .A(_46_),
    .B(_45_),
    .C_N(_44_),
    .D_N(_35_),
    .Y(_37_)
  );
  sky130_fd_sc_hd__nor4bb_1 _51_ (
    .A(_46_),
    .B(_44_),
    .C_N(_35_),
    .D_N(_45_),
    .Y(_38_)
  );
  sky130_fd_sc_hd__nor4bb_1 _52_ (
    .A(_45_),
    .B(_44_),
    .C_N(_35_),
    .D_N(_46_),
    .Y(_40_)
  );
  sky130_fd_sc_hd__nor4b_1 _53_ (
    .A(_46_),
    .B(_45_),
    .C(_44_),
    .D_N(_35_),
    .Y(_36_)
  );
  sky130_fd_sc_hd__and4_1 _54_ (
    .A(_46_),
    .B(_45_),
    .C(_44_),
    .D(_35_),
    .X(_43_)
  );
  assign y_int = { o7, o6, o5, o4, o3, o2, o1, o0 };
  assign _46_ = sel[2];
  assign _45_ = sel[1];
  assign _44_ = sel[0];
  assign _35_ = i;
  assign o6 = _42_;
  assign o5 = _41_;
  assign o3 = _39_;
  assign o1 = _37_;
  assign o2 = _38_;
  assign o4 = _40_;
  assign o0 = _36_;
  assign o7 = _43_;
endmodule
