/* Generated by Yosys 0.47+121 (git sha1 98b4affc4, g++ 13.2.0-23ubuntu4 -fPIC -O3) */




module good_mux(input i0, input i1, input sel, output reg y);
always @ (*)
begin
if(sel)
y<=i1;
else
y<=i0;
end
endmodule
